'use client';

import { useState } from 'react';
import { apiClient } from '@/src/apiHelper/api';
import StudentSearchDropdown from './StudentSearchDropdown';
import DegreeTitleDropdown from './DegreeTitleDropdown';

function CloudIcon() {
  return (
    <svg width="68" height="68" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
      <path d="M7 18H17C19.7614 18 22 15.7614 22 13C22 10.4293 20.0583 8.31278 17.5651 8.03634C16.8466 5.71379 14.6806 4 12.1 4C9.03164 4 6.5118 6.42491 6.35916 9.45538C3.86954 9.77969 2 11.9096 2 14.4412C2 16.9599 4.0401 19 6.55879 19H7" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  );
}

function Stepper() {
  return (
    <div className="mx-auto flex w-full max-w-190 items-center justify-between px-4 sm:px-6">
      <div className="flex items-center gap-3 sm:gap-4">
        <span className="flex h-12 w-12 items-center justify-center rounded-full bg-[#5B21B6] text-xl font-bold text-white font-[family-name:var(--font-display)]">1</span>
        <span className="h-1 w-16 rounded-full bg-[#E4DEF2] sm:w-24" />
      </div>
      <div className="flex items-center gap-3 sm:gap-4">
        <span className="flex h-12 w-12 items-center justify-center rounded-full bg-[#E4DEF2] text-xl font-bold text-[#7A7290] font-[family-name:var(--font-display)]">2</span>
        <span className="h-1 w-16 rounded-full bg-[#E4DEF2] sm:w-24" />
      </div>
      <span className="flex h-12 w-12 items-center justify-center rounded-full bg-[#E4DEF2] text-xl font-bold text-[#7A7290] font-[family-name:var(--font-display)]">3</span>
    </div>
  );
}

export default function IssueCertificateSection() {
  const [studentId, setStudentId] = useState('');
  const [CertificateTitle, setCertificateTitle] = useState('');
  const [file, setFile] = useState<File | null>(null);
  const [uploading, setUploading] = useState(false);
  const [submitting, setSubmitting] = useState(false);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      setFile(e.target.files[0]);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!file) {
      alert('Please upload a document template');
      return;
    }

    if (!studentId) {
      alert('Please select a student');
      return;
    }

    try {
      setSubmitting(true);

      // Upload file to get CID
      setUploading(true);
      const fileFormData = new FormData();
      fileFormData.append('file', file);
      const uploadResponse = await apiClient.uploadFile(fileFormData);
      const cid = uploadResponse.cid || uploadResponse;
      setUploading(false);

      // Issue certificate
      await apiClient.issueCertificate({
        certificateId: `CERT-${Date.now()}`,
        studentId: studentId,
        CertificateTitle: CertificateTitle,
        cid: cid,
        hash: '', // Will be generated by backend
        status: 'ISSUED',
      });

      alert('Certificate issued successfully!');
      setStudentId('');
      setCertificateTitle('');
      setFile(null);
    } catch (error) {
      console.error('Failed to issue certificate:', error);
      alert('Failed to issue certificate. Please try again.');
    } finally {
      setSubmitting(false);
      setUploading(false);
    }
  };

  return (
    <section className="space-y-10 py-8" id="issue-certificate">
      <Stepper />

      <div className="mx-auto w-full max-w-190 rounded-[20px] border border-[#E4DEF2] bg-[#FAF9FC] p-7 shadow-[0_10px_30px_rgba(29,19,48,0.04)] sm:p-9">
        <h2 className="text-[48px] font-black tracking-tight text-[#1D1330] font-[family-name:var(--font-display)]">Issue New Academic Credential</h2>

        <form onSubmit={handleSubmit} className="mt-8 space-y-7">
          <label className="block">
            <span className="mb-2 block text-sm font-semibold text-[#7A7290] font-[family-name:var(--font-display)]">Student Name</span>
            <StudentSearchDropdown
              value={studentId}
              onChange={setStudentId}
              placeholder="Search student by name or index no..."
            />
          </label>

          <label className="block">
            <span className="mb-2 block text-sm font-semibold text-[#7A7290] font-[family-name:var(--font-display)]">Certificate Title</span>
            <DegreeTitleDropdown
              value={CertificateTitle}
              onChange={setCertificateTitle}
              placeholder="Select degree title..."
            />
          </label>

          <div>
            <p className="mb-2 text-sm font-semibold text-[#7A7290] font-[family-name:var(--font-display)]">Upload Document Template</p>
            <label className="flex min-h-50 cursor-pointer flex-col items-center justify-center rounded-[20px] border-2 border-dashed border-[#E4DEF2] bg-[#E4DEF2]/40 px-6 text-center text-[#7A7290] transition-colors hover:border-[#7C3AED] hover:bg-[#7C3AED]/30">
              <span className="mb-3 text-[#7C3AED]">
                <CloudIcon />
              </span>
              <p className="text-[30px] font-medium text-[#7A7290]">
                Drag and drop file or <span className="font-bold text-[#7C3AED]">browse</span>
              </p>
              <p className="mt-2 text-sm">PDF, JPG or PNG (max. 10MB)</p>
              <input type="file" className="hidden" onChange={handleFileChange} accept=".pdf,.jpg,.jpeg,.png" />
            </label>
            {file && (
              <p className="mt-2 text-sm text-[#7C3AED]">Selected: {file.name}</p>
            )}
          </div>

          <button
            type="submit"
            disabled={submitting || uploading}
            className="w-full rounded-[10px] bg-[#5B21B6] px-6 py-5 text-[40px] font-bold tracking-tight text-white shadow-[0_16px_30px_rgba(91,33,182,0.22)] transition-colors hover:bg-[#4C1D95] disabled:opacity-50 disabled:cursor-not-allowed font-[family-name:var(--font-display)]"
          >
            {submitting || uploading ? 'Processing...' : 'Sign & Commit to Blockchain'}
          </button>
        </form>
      </div>
    </section>
  );
}